image: "ruby:2.5"

before_script:
  - ruby -v
  - gem install bundler  --no-document    # Bundler is not installed with the image

rubocop:
  stage: test
  script:
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby
  - bundle exec rubocop

rspec:
  stage: test
  script:
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby
  - bundle exec rspec spec

publish_gem:
  stage: deploy
  only:
    - master
  when: manual
  script:
  - 'bin/build_and_publish'
