image: "ruby:2.5"

before_script:
  - ruby -v
  - gem install bundler  --no-ri --no-rdoc    # Bundler is not installed with the image
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

rubocop:
  script:
  - bundle exec rubocop

rspec:
  script:
  - bundle exec rspec spec