# This is the configuration used to check the rubocop source code.

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Lint/HandleExceptions:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/rspec'

Style/Encoding:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/RescueModifier:
  Enabled: false

# false error when run with Neomake
Naming/FileName:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/RescueStandardError:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'config/**/*.rb'
    - '*.gemspec'
